# Generated by Django 3.0.4 on 2020-04-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(null=True, upload_to='movie_posters'),
        ),
    ]
